---
title: "Monte Carlo Mix"
output:
  html_document: default
  html_notebook: default
---

```{r include=FALSE}

###Loading the packages
library(plyr)
library(tidyverse)
library(reshape2)
library(psych)
library(MASS)
library(scales)
library(gridExtra)
library(grid)
library(knitr)
library(vegan)
library(kableExtra)
library(arrangements)
library(gtable)
library(UpSetR)
library(ggtern)
library(ClusterR)

# load existing functions

#load the modelisation function.
source('Data_generator.R')
#load the correction function.
source('../AbundanceCorrection_2steps_Normalization_Steps.R')
#load the tranformation and kmeans functions.
source('../Kmeans_clustering.R')

prop_HD=c(0.2,0.2,0.2,0.2,0.2)

cells=c('Bcells','Monocytes','Granulocytes','NKcells','Tcells')

```

# (1) Get the data 

```{r GetData, echo=FALSE}

intSites <- read.table(gzfile('../../data/intSites.mergedSamples.collapsed.csv.gz'), sep = ',', header = TRUE)
intSites$key=paste(as.character(intSites$patient),as.character(intSites$timePoint),sep='_')

intSites_new_concat_sup0=read.table('../../data/intSites_new_concat_sup0.csv', sep = ';', header = TRUE)

## Get other values
crossOverReports <- readChar('../../data/crossOverReports.tsv', file.info('../../data/crossOverReports.tsv')$size)

crossOverReports <- unlist(strsplit(crossOverReports, '#%'))
crossOverReports <- unlist(lapply(crossOverReports, function(x){
  source     <- ifelse(grepl('#source:', x), sub('\\t+$', '', str_match(x, '#source:\\s+(.+)')[2]), '')
  cellCounts <- as.numeric(str_match_all(str_match(x, 'initialCellCounts,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  psort <- as.numeric(str_match_all(str_match(x, 'pB_postsort,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  count_psort <-as.numeric(str_match_all(str_match(x, 'postsortCount,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  VCN <-as.numeric(str_match_all(str_match(x, 'VCN,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  DNA <-as.numeric(str_match_all(str_match(x, 'DNA,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  patient    <- str_match(x, '#(\\S+)')[2]
  timePoint  <- str_match(x, '#\\S+\\s+(\\S+)')[2]
  t          <- gsub('\\t+\\n', '\n', substr(x, regexpr('COUNTS', x)+7, nchar(x)))
  m          <- read.table(tc <- textConnection(t), header = TRUE, fill = TRUE, check.names = FALSE, sep='\t'); close(tc); 
  if(nrow(m) < 5 | length(m) < 5) return(NA)
  m <- m[1:5, 1:5]
  r <- list()
  r[[paste(patient, timePoint, source, sep='|')]] <- list(
    patient   = str_match(x, '#(\\S+)\\s+(\\S+)')[2],
    timePoint = str_match(x, '#(\\S+)\\s+(\\S+)')[3],
    source    = source,
    t         = t,
    table     = m,
    cellCount = cellCounts,
    psort     = psort,
    count_psort = count_psort,
    VCN = VCN,
    DNA = DNA)

  r }), recursive = FALSE)

crossOverReports <- crossOverReports[sapply(crossOverReports, is.list)]
crossOverReports <- crossOverReports[grep(names(crossOverReports),pattern='Blood')]  
```


# (2) Get all simulation parameters

## Get all the real data useful for our modelisation
```{r echo=FALSE}

##Select the WAS4|m48 patient
patient='WAS4|m48'

#Filter the data

intSites$key=gsub('_M','\\|m',intSites$key)
intSites=intSites[intSites$key==patient,]
intSites=subset(intSites, cellType %in% c('GRANULOCYTES', 'MONOCYTES', 'BCELLS', 'NKCELLS', 'TCELLS'))

key=paste0(patient,'|Blood')

## Get important values of the tsv file
crossOverReports=crossOverReports[[key]]
VCN=crossOverReports$VCN
VCN_norm=VCN/max(VCN)
DNA=crossOverReports$DNA

## Get the wide dataframe with patient filter
intSites_new_concat_sup0=filter(intSites_new_concat_sup0,key== !!key)


#  **************** calculate estimators **************
indic <-intSites %>%
  dplyr::group_by(patient, timePoint) %>%
  dplyr::summarise(Chao1 = round(estimateR(estAbund, index='chao')[2], 0),
                   ACE= round(estimateR(estAbund, index='chao')[4], 0),
                   Shannon=round(diversity(estAbund),3), 
                   UniqueSites=length(unique(posid)),
                   Inferred_cells=sum(estAbund),
                   percent_sampling = UniqueSites/Chao1) %>% dplyr::ungroup()
indic$mean_cells=mean(intSites_new_concat_sup0$cellCount)
indic$var=var(intSites_new_concat_sup0$cellCount)
indic$lambda=indic$mean_cells/indic$percent_sampling


# contamination matrix
    
matrix=as.matrix(crossOverReports$table)

for (r in 1:nrow(matrix)){
  tab=matrix[r,]
  nb_zero=length(tab[tab == 0])
  if (nb_zero >0){
    percent=0.003/100*nb_zero
    p=(percent)/(1-percent)*sum(tab[tab>0])
    remp=p/nb_zero
    tab[tab==0]=remp
  }
  matrix[r,]=tab
}

#Vector contamination matrix
confusion=as.matrix(matrix)
VCN=matrix(nrow=5,ncol=5,rep(0,5*5))
diag(VCN)=crossOverReports$VCN
confusion=confusion%*%VCN    

#Proportion
conta_prop=prop.table(matrix,2)

rm(intSites)
```


## Simulation with hyper-parameters

```{r Data simulation, echo=FALSE}

cst_var=1.4
prob_type=c(0.6,0.2,0.2)
cst_ab= 1e3

print(paste0("patient :",patient))
print(paste(c("cst_variance :",cst_var,'||',"pourcentage BMGKT :",prob_type[1],'||',"pourcentage GM ",prob_type[2],"pourcentageT ",prob_type[3],'||',"cst_ab pour le sampling :",cst_ab),collapse = " "))

```

# (3) Monte Carlo loop

```{r echo=FALSE, message=FALSE}
debut = Sys.time()
M=50
print(paste0("Monte Carlo replicates = ", M))
means = NULL
vars = NULL
nbIS = NULL
nb_cells = NULL

list_thresholds = c(1:8)
purity = matrix(NA,nrow=M,ncol=length(list_thresholds))
rand = matrix(NA,nrow=M,ncol=length(list_thresholds))
nmi  = matrix(NA,nrow=M,ncol=length(list_thresholds))
entropy = matrix(NA,nrow=M,ncol=length(list_thresholds))

for (m in 1:M){
  print(paste0("Monte Carlo m= ",m))
test=Dataset_creation(prob_type,cst_var,cst_ab,crossOverReports=crossOverReports,indic=indic,loop=TRUE)

data_sim=test$data_sim
repart=test$repart


#### Data repartition estimators (After bias) 

means = c(means,mean(data_sim$cellCount))
vars = c(vars,var(data_sim$cellCount))
nbIS = c(nbIS ,nrow(data_sim))
nb_cells = c(nb_cells,sum(data_sim$cellCount))

##### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ (3) Clustering ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


#loop on threshold
#list_indic_clust=lapply(list_thresholds,function(thre){
  
for (thre in list_thresholds){
  #cat('\n ABUNDANCE THRESHOLD : ',thre,'\n')

### Apply the threshold
data_threshold=filter(data_sim,Granulocytes>=thre|Monocytes>=thre|Bcells>=thre|NKcells>=thre|Tcells>=thre)

### ************* Apply the correction *************
 
    correction=Correction_2steps_Normalization(x=crossOverReports,d2=data_threshold)
    data_corrected=correction$data_corrected_final
    colnames(data_corrected)=c('posid','gene',paste0(cells,'_corrected'))
    
    # Add the proportions
    prop = (data_corrected[,grepl("_corrected",names(data_corrected))])/
      rowSums((data_corrected[,grepl("corrected",names(data_corrected))]))
    names(prop) = c("Bcells_corrected_prop", "Monocytes_corrected_prop", "Granulocytes_corrected_prop",
                    "NKcells_corrected_prop", "Tcells_corrected_prop")
    intSites_new = cbind(data_corrected,prop)

    
### ************* Apply the clustering *************

   intSites_new$key='pat|mxx|Blood'
   kmean= KmeansClustering(intSites_new,HD=prop_HD)
   kmean_IS=kmean$intSites_withKmeans
   
   #Add the real IS type
   kmean_IS=left_join(kmean_IS,data_sim[,c('posid','type')])
   

  #clustering quality
  nb_cluster = kmean$nbclust_estim
 purity[m,thre]=   external_validation(as.numeric(factor(kmean_IS$type)),as.numeric(factor(kmean_IS$cluster)),
                                  method = c('purity'))
 rand[m,thre]= external_validation(as.numeric(factor(kmean_IS$type)),as.numeric(factor(kmean_IS$cluster)),
                                  method = c('adjusted_rand_index'))
 nmi[m,thre]= external_validation(as.numeric(factor(kmean_IS$type)),as.numeric(factor(kmean_IS$cluster)),
                                  method = c('nmi'))
 entropy[m,thre] = external_validation(as.numeric(factor(kmean_IS$type)),as.numeric(factor(kmean_IS$cluster)),
                                  method = c('entropy'))
 

}
}

fin = Sys.time()
print(paste(c('Time for', m ,'Monte Carlo replicates=', round(fin-debut,digits = 2) ,'min'), collapse = ' '))
```

```{r, results='asis'}
indic_sim=data.frame(n_sim = c(1:M),means,vars,nbIS,nb_cells)
print(indic_sim)
cat('\n')

#Mean Ab
indic_to_show=tibble(indic$mean_cells, mean(indic_sim$means), sd(indic_sim$means))
colnames(indic_to_show)=c('real mean Abundance','Mean on the 50 trials','SD on the 50 trials')
print(kable(indic_to_show)%>%kable_styling())

cat('\n')

#Var Ab
indic_to_show=tibble(indic$var, mean(indic_sim$vars), sd(indic_sim$vars))
colnames(indic_to_show)=c('real var Abundance','Mean on the 50 trials','SD on the 50 trials')
print(kable(indic_to_show)%>%kable_styling())
cat('\n')

#nb IS
indic_to_show=tibble(indic$UniqueSites, mean(indic_sim$nbIS), sd(indic_sim$nbIS))
colnames(indic_to_show)=c('real nb of IS','Mean on the 50 trials','SD on the 50 trials')
print(kable(indic_to_show)%>%kable_styling())
cat('\n')

#nb cells
indic_to_show=tibble(indic$Inferred_cells, mean(indic_sim$nb_cells), sd(indic_sim$nb_cells))
colnames(indic_to_show)=c('real nb of cells','Mean on the 50 trials','SD on the 50 trials')
print(kable(indic_to_show)%>%kable_styling())
cat('\n')


```



```{r echo=FALSE, fig.width=10, fig.height=5}

# All values

val=as.data.frame(rbind(purity,nmi,rand))
colnames(val)=1:8
val$type=rep(c('purity','nmi','rand'),each=M)

plotdata=melt(val)

ggplot(data=plotdata)+geom_boxplot(aes(x=as.factor(variable),y=value,color=type))+labs(x='Thresholds')+theme_bw()
ggplot(data=plotdata)+geom_boxplot(aes(x=as.factor(variable),y=value,color=type))+labs(x='Thresholds')+theme_bw()+facet_wrap(~type)

# Mean aggregate

clustering_indicators = tibble(thresholds = list_thresholds  , 
                               purity = colMeans(purity),
                               rand = colMeans(rand),
                               nmi=colMeans(nmi))
clustering_indicators=melt(clustering_indicators,id.vars = 'thresholds')


clustering_indicators2 = tibble(thresholds = list_thresholds  , 
                               purity=apply(purity, 2, sd),
                               rand=apply(rand, 2, sd),
                               nmi=apply(nmi, 2, sd)
                               )
clustering_indicators2=melt(clustering_indicators2,id.vars = 'thresholds')


cl_ind=merge(clustering_indicators,clustering_indicators2,by=c("thresholds","variable"))
colnames(cl_ind)=c("thresholds","var","mean","sd")


ggplot(data=cl_ind)+geom_line(aes(x=thresholds,y=mean,color=var))+
  geom_line(aes(x=thresholds,y=mean-2*sd,color=var),linetype='dotted')+
  geom_line(aes(x=thresholds,y=mean+2*sd,color=var),linetype='dotted')+theme_bw()+labs(x='Threshold',y='',color='')

```

