---
fontsize: 11pt
geometry: margin=0.25in
output:
  html_document:
    keep_md: no
---


```{r DataPrep,  include=FALSE}

###Loading the packages
library(plyr)
library(tidyverse)
library(reshape2)
library(psych)
library(MASS)
library(scales)
library(gridExtra)
library(grid)
library(knitr)
library(vegan)
library(kableExtra)
library(DataCombine)

# intSites_original <- read.table('../Data/intSites.mergedSamples.collapsed.csv', sep = ',', header = TRUE)
intSites_original <- read.table(gzfile('../data/intSites.mergedSamples.collapsed.csv.gz'), sep = ',', header = TRUE)
     
intSites=intSites_original
intSites$key=paste(as.character(intSites$patient),as.character(intSites$timePoint),sep='_')

intSites=subset(intSites,key%in%c('WAS2_M22','WAS2_M48','WAS2_M78','WAS4_M12','WAS4_M36','WAS4_M48','WAS4_M60',
                                  'WAS5_M12.6','WAS5_M36','WAS5_M43','WAS5_M55','WAS7_M12','WAS7_M30','WAS7_M48',
                                  'b0/bE_M11','b0/bE_M36','b0/bE_M48','bS/bS_M12','bS/bS_M24'))

intSites=subset(intSites, cellType %in% c('GRANULOCYTES', 'MONOCYTES', 'BCELLS', 'NKCELLS', 'TCELLS'))


# For each patient / timePoint combination, calculate estimators of each cell types.
indic <-intSites %>%
  dplyr::group_by(patient, timePoint, cellType) %>%
  dplyr::summarise(Chao1 = round(estimateR(estAbund, index='chao')[2], 0),
                   ACE= round(estimateR(estAbund, index='chao')[4], 0),
                   Shannon=round(diversity(estAbund),3), 
                   UniqueSites=length(unique(posid)),
                   Inferred_cells=sum(estAbund),
                   Total_reads=sum(reads)) %>% dplyr::ungroup()

colnames(indic)<-c('Patient','Timepoint','CellType','Chao1','ACE','Shannon','UniqueSites','Inferred cells','Total  Reads')

#Order the patient and the cell types.
indic$Patient=factor(indic$Patient,levels=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'))
indic$CellType=factor(indic$CellType,
                      levels=toupper(c('Granulocytes','Monocytes','Bcells','NKcells','Tcells')),
                      labels=c('G','M','B','K','T'))
indic$Timepoint=as.numeric(gsub('M','',indic$Timepoint))
indic$Source=ifelse(indic$Patient%in%c('WAS4','WAS5','bS/bS'),'BM','MPB')


## Add values present in the crossOverReports file

options(stringsAsFactors = FALSE)
### crossOverReports <- readChar('../Data/crossOverReports.tsv', file.info('../Data/crossOverReports.tsv')$size)
crossOverReports <- readChar('../data/crossOverReports.tsv', file.info('../data/crossOverReports.tsv')$size)

crossOverReports <- unlist(strsplit(crossOverReports, '#%'))
crossOverReports <- unlist(lapply(crossOverReports, function(x){
  source     <- ifelse(grepl('#source:', x), sub('\\t+$', '', str_match(x, '#source:\\s+(.+)')[2]), '')
  cellCounts <- as.numeric(str_match_all(str_match(x, 'initialCellCounts,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  psort <- as.numeric(str_match_all(str_match(x, 'pB_postsort,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  count_psort <-as.numeric(str_match_all(str_match(x, 'postsortCount,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  VCN <-as.numeric(str_match_all(str_match(x, 'VCN,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  DNA <-as.numeric(str_match_all(str_match(x, 'DNA,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  patient    <- str_match(x, '#(\\S+)')[2]
  timePoint  <- str_match(x, '#\\S+\\s+(\\S+)')[2]
  t          <- gsub('\\t+\\n', '\n', substr(x, regexpr('COUNTS', x)+7, nchar(x)))
  m          <- read.table(tc <- textConnection(t), header = TRUE, fill = TRUE, check.names = FALSE, sep='\t'); close(tc); 
  if(nrow(m) < 5 | length(m) < 5) return(NA)
  m <- m[1:5, 1:5]
  r <- list()
  r[[paste(patient, timePoint, source, sep='|')]] <- list(
    patient   = str_match(x, '#(\\S+)\\s+(\\S+)')[2],
    timePoint = str_match(x, '#(\\S+)\\s+(\\S+)')[3],
    source    = source,
    t         = t,
    table     = m,
    cellCount = cellCounts,
    psort     = psort,
    count_psort = count_psort,
    VCN = VCN,
    DNA = DNA)

  r }), recursive = FALSE)

crossOverReports <- crossOverReports[sapply(crossOverReports, is.list)]
crossOverReports <- crossOverReports[grep(names(crossOverReports),pattern='Blood')]  

# VCN
vcn=as.data.frame(do.call(rbind,lapply(names(crossOverReports),function(x){
                                 dat=crossOverReports[[x]]$VCN })))

colnames(vcn)<-c('B','M','G','K','T')

vcn$Patient=gsub('\\|.*','',names(crossOverReports))
vcn$Timepoint=gsub("|\\|B.*|.*m", "", names(crossOverReports))
vcn=melt(vcn,id.vars = c('Patient','Timepoint'))
colnames(vcn)=c('Patient','Timepoint','CellType','VCN')


# Count psort
psc=do.call(rbind,lapply(names(crossOverReports),function(x){
                                 dat=crossOverReports[[x]]$count_psort}))
colnames(psc)<-c('B','M','G','K','T')

dna=do.call(rbind,lapply(names(crossOverReports),function(x){
                                 dat=crossOverReports[[x]]$DNA
                                 }))
colnames(dna)<-c('B','M','G','K','T')

data_cross=cbind(vcn,melt(psc)$value,melt(dna)$value)
colnames(data_cross)=c('Patient','Timepoint','CellType','VCN','PSC','DNA')


indic=merge(indic,data_cross,by=c('Patient','Timepoint','CellType'))
indic$key=paste0(indic$Patient,'_',indic$Timepoint)

##  Chao1 Normalized
indic$chao1_norm=ifelse(indic$VCN>1,indic$Chao1/indic$VCN,indic$Chao1 )

## ACE Normalized
indic$ACE_norm=ifelse(indic$VCN>1,indic$ACE/indic$VCN,indic$ACE )

##log10 Chao1 Normalized
indic$chao1_norm_log=log10(indic$chao1_norm)


#############################################################
### Other information for a given tmpt, for Granulocytes ###
#############################################################

indic_selec=subset(indic,key%in%c('WAS4_48','WAS5_55','bS/bS_24','WAS2_78','WAS7_48','b0/bE_48') &
                        CellType=='G')

## CD34
CD34=data.frame(Patient=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'),val=c(65.7,70.584,226.8,660,177.3,557.6))
CD34$Source=ifelse(CD34$Patient%in%c('WAS4','WAS5','bS/bS'),'BM','MPB')
colnames(CD34)=c('Patient','CD34','Source')

indic_selec$CD34=CD34[match(indic_selec$Patient,CD34$Patient),'CD34']
indic_selec$chao1_norm_div_CD34=indic_selec$chao1_norm/indic_selec$CD34

## CD34 per kg
CD34perkg=data.frame(Patient=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'),val=c(7.3,4.08,5.6,11,9,13.6))
CD34perkg$Source=ifelse(CD34perkg$Patient%in%c('WAS4','WAS5','bS/bS'),'BM','MPB')
colnames(CD34perkg)=c('Patient','CD34perkg','Source')

indic_selec$CD34perkg=CD34perkg[match(indic_selec$Patient,CD34perkg$Patient),'CD34perkg']
indic_selec$chao1_norm_div_CD34perkg=indic_selec$chao1_norm/indic_selec$CD34perkg

## Age
Age=data.frame(Patient=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'),val=c(0.8,3,13,15,3.5,16))
Age$Source=ifelse(Age$Patient%in%c('WAS4','WAS5','bS/bS'),'BM','MPB')
colnames(Age)=c('Patient','Age','Source')

##log10 Chao1 Normalized
indic_selec$chao1_norm_log=log10(indic_selec$chao1_norm)

```

```{r GlobalValues, include=FALSE, message=FALSE, warning=FALSE}

## Determine a general element theme for the different plots
th=theme_bw()+
   theme(text=element_text(family='ArialMT',size=23, colour='black',face='bold'),
         panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
         strip.background=element_rect(fill=NA, color=NA),
         strip.text=element_text(family='ArialMT',size=32,colour='black',face='bold'),
         axis.text=element_text(family='ArialMT',size=18, colour='black',face='bold'),
          axis.title=element_text(family='ArialMT',size=27, colour='black',face='bold'),
         plot.title=element_text(family='ArialMT',size=32, colour='black',face='bold'),
         legend.text=element_text(family='ArialMT',size=24.5, colour='black',face='bold'))

th_small=theme_bw()+
   theme(text=element_text(family='ArialMT',size=23, colour='black',face='bold'),
         panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
         strip.background=element_rect(fill=NA, color=NA),
         strip.text=element_text(family='ArialMT',size=32,colour='black',face='bold'),
         axis.text=element_text(family='ArialMT',size=18, colour='black',face='bold'),
         axis.title=element_text(family='ArialMT',size=27, colour='black',face='bold'),
         plot.title=element_text(family='ArialMT',size=32, colour='black',face='bold'),
         legend.text=element_text(family='ArialMT',size=24.5, colour='black',face='bold'))


### Fix the colors and order of the clusters
colors <- c(GMBKT='mediumorchid4',GMKT='darkorchid',GMBT='blueviolet',GMBK='mediumpurple4',GBKT='magenta4',MBKT='hotpink4',
            GMB='forestgreen',GMK='deepskyblue3',GMT='thistle4',GBT='lemonchiffon2',GBK='aquamarine3',GKT='thistle3',
            MBT='sienna3',MBK='honeydew3',MKT='lightpink4',BKT='coral2',
            MB='cornsilk3',MK='plum3',GB='green3',GK='cadetblue4',GM='deepskyblue4',GT='darkslateblue',MT='red4',
            BK='lightseagreen',BT='darkorange2',KT='hotpink3',
            T='red3',B='lightgoldenrod',K='turquoise2',G='royalblue4',M='gray22','[Blood]'='black')

fac=c('GMBKT',"GMKT",'GMBT','GMBK','GBKT','MBKT','GMK','GMB','GMT','GBT','GBK','GKT',
      'MBK','MBT','MKT','BKT','MB','MK','MT', 'GM', 'GB','GK','GT', 'BK','BT','KT','G','M','B','K','T')

### Patients 
patient_samp=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE')


samples=c("WAS4|m48|Blood" ,"WAS5|m55|Blood", "bS/bS|m24|Blood",
          "WAS2|m78|Blood" ,"WAS7|m48|Blood", "b0/bE|m48|Blood")

indic$Patient_name=factor(indic$Patient,levels=levels(indic$Patient),
                         labels=c('WAS4','WAS5','\u03B2S/\u03B2S',
                                 'WAS2','WAS7',"\u03B20/\u03B2E"))

indic_selec$Patient_name=factor(indic_selec$Patient,levels=levels(indic_selec$Patient),
                         labels=c('WAS4','WAS5','\u03B2S/\u03B2S',
                                 'WAS2','WAS7',"\u03B20/\u03B2E"))

```


##### Figure 2A & 2B 

```{r Fig2AB, echo=FALSE, fig.height=13, fig.width=20, dev='png',dpi=350}
  
#A
A=ggplot(data=indic,aes(x=Timepoint,y=UniqueSites,colour=Patient_name,shape=Source))+
  geom_point(size=7)+
  geom_line(size=0.8)+
  facet_wrap(~CellType,nrow=1,scales='free')+
  scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
  scale_y_continuous(limits=c(min(indic$UniqueSites),max(indic$UniqueSites)))+
  scale_shape_manual('',values=c(16,15))+
  labs(y='Unique Sites',x='Months post gene therapy',colour='')+
  th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+    
  guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
         shape=guide_legend(nrow=1))
  

#B
B=ggplot(data=indic,aes(x=Timepoint,colour=Patient_name,y=Shannon,shape=Source))+geom_point(size=7)+
  geom_line(aes(y=Shannon,group=Patient),size=0.8)+
  facet_wrap(~CellType,nrow=1,scales='free')+
  scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
  scale_y_continuous(limits=c(0,max(indic$Shannon)))+
  scale_shape_manual('',values=c(16,15))+
  labs(y='Shannon Index',x='Months post gene therapy',colour='')+
  th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+    
  guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
         shape=guide_legend(nrow=1))

  #Print the plots in the same panel.
  grid.arrange(A,B,ncol=1)
```


##### Figure 3A & 3B

```{r  Fig3AB, echo=FALSE, fig.height=7, fig.width=16, dev='png',dpi=350}

CHAO=ggplot(indic_selec, aes(x=Source,y=chao1_norm))+geom_boxplot()+
     geom_jitter(width = 0.01, height = 0, aes(colour=Patient_name,shape=Source),size=5)+
     scale_y_log10(limits = c(1,1e6),
                   expand = c(0,0),breaks=10^(0:6),
                   labels = trans_format("log10", math_format(10^.x)))+
     scale_shape_manual('',values=c(16,15))+
     labs(y='Est. active HSC number (log)',x='',colour='',subtitle='')+
     th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0),
                     axis.text.x=element_text(family='ArialMT',size=22, colour='black',face='bold'))+    
     guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),byrow=T),
            shape=guide_legend(nrow=2,byrow=TRUE))
  

CHAO_CD=ggplot(indic_selec, aes(x=Source,y=chao1_norm_div_CD34))+geom_boxplot()+
        geom_jitter(width = 0.01, height = 0,aes(colour=Patient_name,shape=Source),size=5)+
        scale_shape_manual('',values=c(16,15))+
        labs(y= expression(atop('Est. active HSC number',paste('/',10^6,' infused CD34'))),x='',colour='',subtitle='')+
        th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0), 
                       axis.text.x=element_text(family='ArialMT',size=22, colour='black',face='bold'))+    
        guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),byrow=T),
               shape=guide_legend(nrow=2,byrow=TRUE))
  
  #Print the plots in the same panel.
  grid.arrange(CHAO, CHAO_CD,nrow=1)

```


##### _Figure 3C :log10(CHAO1 normalized) VS CD34 per kg all celltypes_

```{r Fig3C, echo=FALSE, fig.height=7, fig.width=8, dev='png',dpi=350,out.width = "50%"}

  ## Get the data
  plots=list()
  C='G'

  indic_selec_allcell=subset(indic,key%in%c('WAS4_48','WAS5_55','bS/bS_24','WAS2_78','WAS7_48','b0/bE_48') &
                        CellType==C)
  indic_selec_allcell$CD34perkg=CD34perkg[match(indic_selec_allcell$Patient,CD34perkg$Patient),'CD34perkg']

  r=corr.test(indic_selec_allcell[,c('CD34perkg','chao1_norm_log')])

## plot
   ggplot(indic_selec_allcell, aes(x=CD34perkg,y=chao1_norm))+ 
   geom_point(aes(group=Patient,colour=Patient_name,shape=Source),size=7)+
   geom_smooth(method=lm, se=TRUE,fill = "gray20",colour='black',alpha=0.07)+
   scale_y_log10(limits = c(1,1e6), expand = c(0,0),breaks=10^(0:6),labels = trans_format("log10", math_format(10^.x)))+
   scale_shape_manual('',values=c(16,15))+
   labs(y=paste0('Est. active HSC number (log)'),x='Corrected CD34 per kg',colour='',
       title=paste('r =',round(r$r[2],3)),
       subtitle=paste('p =',round(r$p[2],3)))+
  th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
  guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),byrow=T),
         shape=guide_legend(nrow=2,byrow=TRUE))

```


##### _Figure 3D :CD34 per kg VS mean abundance_

```{r Fig3D, echo=FALSE, fig.height=7, fig.width=8, dev='png',dpi=350, out.width = "50%"}

## Get the data.

intSites$timePoint=tolower(intSites$timePoint)
intSites$key <- paste(intSites$posid, intSites$cellType, intSites$patient, intSites$timePoint)

## Put the data in a wide format count table.
  
  assign(paste('liste_intSites_new_sup',0,sep=''),lapply(crossOverReports,function(x){  
   
     if(x$source == 'BoneMarrow') names(x$table) <- paste0('BM_', names(x$table))
    
    # Subset the intSite data to include only sites from a specific cell type and time point.
    i <- which(intSites$patient==x$patient & intSites$timePoint==x$timePoint &
                 toupper(intSites$cellType) %in% toupper(names(x$table)))
    d <- intSites[i,]
    
    if(nrow(d) == 0) stop(paste0(x$patient, ' / ', x$timePoint, ' could not be found in the intSite data.'))
    
    
    # Replace NA gene names with 'NONE' in case a function is sensitive to NA.
    if(length(which(is.na(d$nearestFeature))) > 0) d[which(is.na(d$nearestFeature)),]$nearestFeature <- 'NONE'
    
    # Reorganize the data to create an intSite / cell count table.
    d2 <- reshape2::dcast(d, posid ~ cellType, value.var='estAbund', fun.aggregate=function(x){x[1]}, fill=0)  
    
    # Add missing cell types.
    d2[names(x$table)[! toupper(names(x$table)) %in% toupper(names(d2))]] <- 0
    
    # Add nearest gene column.
    d2$gene <- intSites[match(d2$posid, intSites$posid),]$nearestFeature  
    
    # Add inFeature column.
    d2$inFeature <- intSites[match(d2$posid, intSites$posid),]$inFeature  
    
    # Reorganize the column headers.
    d2 <- d2[,c(1,grep('gene',   names(d2), ignore.case = TRUE),
                 grep('BCELL',  names(d2), ignore.case = TRUE),
                 grep('MONO',   names(d2), ignore.case = TRUE),
                 grep('GRANULO', names(d2), ignore.case = TRUE),
                 grep('NKCELL', names(d2), ignore.case = TRUE),
                 grep('TCELL',  names(d2), ignore.case = TRUE),
                 grep('inFeature',  names(d2), ignore.case = TRUE)
                )]
    
    # Create a cell count column.
    d2$cellCount <-  apply(d2, 1, function(x){ sum(as.integer(x[3:7])) })
    
    # Rename the input columns.
    names(d2)=c("integrationSite", "gene", "Bcells", "Monocytes", "Granulocytes", "NKcells", "Tcells","inFeature", "cellCount") 
    
    d2$integrationSite=as.character(d2$integrationSite)
    d2$gene=as.character(d2$gene)
    d2$key <- paste(c(x$patient, x$timePoint,x$source),collapse = "|") 
    
    intSites_new=d2
  
    return(intSites_new)
    } ))
  

  # Reunite all the data sup0 (without threshold) in a unique dataframe.
  intSites_new_concat_sup0=do.call(rbind,liste_intSites_new_sup0)
  
  # Calculate the mean values.
  
  D=intSites_new_concat_sup0
  plotData=D[D$key%in%samples,]

  m=aggregate(plotData$cellCount,list(plotData$key),mean)
  m$patient=gsub('\\|.*','',m$Group.1)
  colnames(m)<-c("key",'mean','Patient')
  m$Source=ifelse(m$Patient%in%c('WAS4','WAS5','bS/bS'),'BM','MPB')
  colnames(m)=c("key",'mean','Patient','Source')
    

  ##### 34 per kg VS mean study
  dat=merge(CD34perkg,m,by='Patient')
  dat$Patient=factor(dat$Patient,
                     levels=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'), 
                     labels=c('WAS4','WAS5','\u03B2S/\u03B2S','WAS2','WAS7',"\u03B20/\u03B2E"))

  r=corr.test(dat[,c('mean','CD34perkg')])

  ## Plot
  ggplot(dat, aes(x=CD34perkg,y=mean))+ 
  geom_point(aes(colour=Patient,shape=Source.x),size=7)+   
  geom_smooth(method=lm, se=TRUE,fill = "gray20",colour='black',alpha=0.07)+
  scale_shape_manual('',values=c(16,15))+
  labs(x='Corrected CD34 per kg',y='Mean IS Abundance',colour='',
     title=paste('r =',round(r$r[2],3)),
     subtitle=paste('p =',round(r$p[2],3)))+
  th_small+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
  guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),byrow=T),
         shape=guide_legend(nrow=2))

```

______________________________________________________________________

#### _Supplementary Figure_
______________________________________________________________________


##### Supplemental Figure 2

```{r SuppFig2 , echo=FALSE, warning=FALSE, fig.height=25, fig.width=20, dev='png',dpi=350}

  # VCN
  A=ggplot(data=indic,aes(x=Timepoint,y=VCN,colour=Patient_name,shape=Source))+geom_point(size=7)+
    geom_line(aes(group=Patient),size=0.8)+
    facet_wrap(~CellType,nrow=1,scales='free')+
    scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
    scale_y_continuous(limits=c(min(indic$VCN,na.rm = T),max(indic$VCN,na.rm = T)))+
    scale_shape_manual('',values=c(16,15))+
    labs(y='VCN',x='Months post gene therapy',colour='')+
    th+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
    guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
           shape=guide_legend(nrow=1,byrow=TRUE))

  # POST SORT COUNT
  B=ggplot(data=indic,aes(x=Timepoint,y=PSC,colour=Patient_name,shape=Source))+geom_point(size=7)+
    geom_line(aes(group=Patient),size=0.8)+
    facet_wrap(~CellType,nrow=1,scales='free')+
    scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
    scale_y_continuous(limits=c(min(indic$PSC),max(indic$PSC)))+
    scale_shape_manual('',values=c(16,15))+
    labs(y='post-sort cell count',x='Months post gene therapy',colour='')+
    th+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
    guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
           shape=guide_legend(nrow=1,byrow=TRUE))

  ## DNA
  C=ggplot(data=indic,aes(x=Timepoint,y=DNA,colour=Patient_name,shape=Source))+geom_point(size=7)+
    geom_line(aes(group=Patient),size=0.8)+
    facet_wrap(~CellType,nrow=1,scales='free')+
    scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
    scale_y_continuous(limits=c(min(indic$DNA,na.rm = T),max(indic$DNA,na.rm = T)))+
    scale_shape_manual('',values=c(16,15))+
    labs(y='DNA (ng)',x='Months post gene therapy',colour='')+
    th+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
    guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
           shape=guide_legend(nrow=1,byrow=TRUE))

# INPUT VECTOR

  data_all=indic
  data_all$input=(data_all$DNA/0.0066)*data_all$VCN

  D=ggplot(data=data_all,aes(x=Timepoint,y=input,colour=Patient_name,shape=Source))+geom_point(size=7)+
  geom_line(aes(group=Patient),size=0.8)+
  facet_wrap(~CellType,nrow=1,scales='free')+
  scale_x_continuous(breaks=seq(from=10,to=80,by=10))+
  scale_y_continuous(limits=c(min(data_all$input,na.rm = T),max(data_all$input,na.rm = T)))+
  scale_shape_manual('',values=c(16,15))+
  labs(y='Input vector',x='Months post gene therapy',colour='')+
  th+theme(legend.position='bottom',strip.text.y = element_text(angle = 0))+
  guides(colour = guide_legend(override.aes=list(shape = c(16,16,16,15,15,15), size = 6, linetype = 0),nrow=1),
         shape=guide_legend(nrow=1,byrow=TRUE))

  #print all the plots in the same panel.
  grid.arrange(A,B,C,D,ncol=1)

```


______________________________________________________________________

### _Supplementary table 1_
______________________________________________________________________



```{r SupTable1,echo=FALSE,fig.width=14,fig.height=20}

   ## Format the data
  indic$CellType=factor(indic$CellType,levels=c("G","M","B","K","T"))
  indic$Timepoint=as.character(indic$Timepoint)
  indic$chao1_norm=round(indic$chao1_norm)
  indic$ACE_norm=round(indic$chao1_norm)

  indic=arrange(indic,Patient,Timepoint,CellType)
  IND=indic[,c( 'Source','Patient',	'Timepoint',	'CellType','UniqueSites',
                "Inferred cells","Total  Reads" ,'Chao1',		'chao1_norm')]
  colnames(IND)<-c('Source','Patient',	'Time\npoint',	'Cell\nType','Unique\nSites',
                   "Inferred\ncells","Total\nReads" ,	'Chao1',		'Chao1_norm')

  ## Add the Total Values
  n=rep('Total',nrow(intSites))

  indic_TOT <-intSites %>% 
  mutate(cell=n)%>%
  dplyr::group_by(patient, timePoint,cell) %>%
  dplyr::summarise(
                   UniqueSites=length(unique(posid)),
                   Inferred_cells=sum(estAbund),
                   Total_reads=sum(reads)) %>% dplyr::ungroup()

  colnames(indic_TOT)<-c('Patient','Timepoint','Cell Type','UniqueSites','Inferred cells','Total  Reads')
  indic_TOT$Source=ifelse(indic_TOT$Patient%in% c( 'WAS4','WAS5','bS/bS'),'BM','MPB')
  indic_TOT$Timepoint=gsub('M','',indic_TOT$Timepoint)
  
  indic_TOT$`Cell Type`='Total'
  indic_TOT$Chao1=''
  indic_TOT$Chao1_norm=''

  indic_TOT= indic_TOT %>% dplyr::select(Source, everything())

  indic_TOT$Patient=factor(indic_TOT$Patient,levels=c('WAS4','WAS5','bS/bS','WAS2','WAS7','b0/bE'))
  indic_TOT=arrange(indic_TOT,Patient)

  Data=IND
  levels(Data$`Cell\nType`)=c(levels(Data$`Cell\nType`),'Total')


  # insert the total values in the dataframe
  row_num=c(seq(6,6*13,by=6),seq(6*13+5,nrow(Data)+nrow(indic_TOT),by=6))

  for(j in 1:nrow(indic_TOT)){
    Data <- InsertRow(Data, NewRow = indic_TOT[j,], RowNum = row_num[j])
  }
  rownames(Data)<-NULL



  ### Print the values in a table.
  kable(Data[1:113,],format='html', align = "c") %>%
  kable_styling(c("striped", "bordered" ,"condensed"),full_width = F,font_size = 8) %>%
  column_spec(1, bold = T, border_right = T,border_left=T) %>%
  column_spec(2, bold = T, border_right = T) %>%
  row_spec( 0, font_size=9) %>%
  row_spec( cumsum(as.vector(aggregate(indic$Source,by=list(indic$Patient),length)$x)), hline_after = T ) %>%
  row_spec( row_num, bold=T) %>%
  collapse_rows(columns = 1:3)
```

