---
fontsize: 11pt
geometry: margin=0.25in
output:
  html_document:
    keep_md: no
---

```{r DataPrep, echo=FALSE, eval=TRUE,warning=FALSE,message=FALSE}

########################################################################
######################## DATA PREPARATION ##############################
########################################################################


###Loading the packages
library(plyr)
library(tidyverse)
library(reshape2)
library(lazyeval)
library(psych)
library(MASS)
library(scales)
library(gridExtra)
library(grid)
library(knitr)
library(gtools)
library(RColorBrewer)

##################################
### Data loading and formatting  ###
#################################

### intSites_original <- read.csv('../../Data/WithReplicates/intSites.noMergedSamples.csv', header = TRUE,stringsAsFactors = TRUE)
intSites_original <- read.table(gzfile('../data/intSites.noMergedSamples.csv.gz'), sep = ',', header = TRUE)


intSites_original$timePoint <- as.character(intSites_original$timePoint)
intSites_original[which(intSites_original$timePoint == 'Y1'),]$timePoint <- 'M12'
intSites_original[which(intSites_original$timePoint == 'Y2'),]$timePoint <- 'M24'
intSites_original[which(intSites_original$timePoint == 'Y3'),]$timePoint <- 'M36'
intSites_original[which(intSites_original$timePoint == 'Y4'),]$timePoint <- 'M48'
intSites_original[which(intSites_original$timePoint == 'Y5'),]$timePoint <- 'M60'
intSites_original$timePoint <- factor(intSites_original$timePoint)



intSites <- data.frame(intSites_original) %>%
            dplyr::group_by(sampleName, posid) %>%
            dplyr::mutate(estAbund = n_distinct(paste(start, end))) %>%
            dplyr::mutate(reads = sum(reads)) %>%
            dplyr::slice(1) %>%
            GenomicRanges::makeGRangesFromDataFrame(keep.extra.columns = TRUE)

intSites=data.frame(intSites@elementMetadata)


 for(i in c('estAbund')) intSites[[i]] <- as.numeric(intSites[[i]]) 
 intSites$cellType=factor(intSites$cellType,levels=levels(intSites$cellType),
                          labels=c( "Bcells","Granulocytes" ,
                                    "Monocytes", "NKcells","Tcells" )) 
 
#Formatting the data.
intSites$sampleName=as.character(intSites$sampleName)
intSites$GTSP=as.character(intSites$GTSP)
intSites$posid=as.character(intSites$posid)
intSites$timePoint=tolower(intSites$timePoint)
intSites$key <- paste(intSites$posid, intSites$cellType, intSites$patient, intSites$timePoint)

#
# Read in the cell sorting cross over reports which are stored in a single file with records separated with '#%'.
# The counts table is identifiable by the key word COUNTS. 
#

options(stringsAsFactors = FALSE)
crossOverReports <- readChar('../data/crossOverReports.tsv', file.info('../data/crossOverReports.tsv')$size)
crossOverReports <- unlist(strsplit(crossOverReports, '#%'))
crossOverReports <- unlist(lapply(crossOverReports, function(x){
  source     <- ifelse(grepl('#source:', x), sub('\\t+$', '', str_match(x, '#source:\\s+(.+)')[2]), '')
  cellCounts <- as.numeric(str_match_all(str_match(x, 'initialCellCounts,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  psort <- as.numeric(str_match_all(str_match(x, 'pB_postsort,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  count_psort <-as.numeric(str_match_all(str_match(x, 'postsortCount,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  VCN <-as.numeric(str_match_all(str_match(x, 'VCN,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  DNA <-as.numeric(str_match_all(str_match(x, 'DNA,(.+)')[2], '([\\d\\.]+)')[[1]][,2])
  patient    <- str_match(x, '#(\\S+)')[2]
  timePoint  <- str_match(x, '#\\S+\\s+(\\S+)')[2]
  t          <- gsub('\\t+\\n', '\n', substr(x, regexpr('COUNTS', x)+7, nchar(x)))
  m          <- read.table(tc <- textConnection(t), header = TRUE, fill = TRUE, check.names = FALSE, sep='\t'); close(tc); 
  if(nrow(m) < 5 | length(m) < 5) return(NA)
  m <- m[1:5, 1:5]
  r <- list()
  r[[paste(patient, timePoint, source, sep='|')]] <- list(
    patient   = str_match(x, '#(\\S+)\\s+(\\S+)')[2],
    timePoint = str_match(x, '#(\\S+)\\s+(\\S+)')[3],
    source    = source,
    t         = t,
    table     = m,
    cellCount = cellCounts,
    psort     = psort,
    count_psort = count_psort,
    VCN = VCN,
    DNA = DNA)
  
  message('Read in ', names(r))
  r
}), recursive = FALSE)

crossOverReports <- crossOverReports[sapply(crossOverReports, is.list)]

```
  
  
```{r GlobalParameters,  echo=FALSE, message=FALSE, warning=FALSE}

##################################################################### 
####################### GLOBAL PARAMETERS ###########################
##################################################################### 

celltype=c( "Granulocytes", "Monocytes", "Bcells", "NKcells", "Tcells")

# Determine general element themes for the plots:

   th_small=theme_bw()+
   theme(text=element_text(family='ArialMT',size=24, colour='black',face='bold'),
         panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
         strip.background=element_rect(fill=NA, color=NA),
         strip.text=element_text(family='ArialMT',size=22,colour='black',face='bold'),
         axis.text=element_text(family='ArialMT',size=16, colour='black',face='bold'),
         plot.title=element_text(family='ArialMT',size=25, colour='black',face='bold'),
         legend.title=element_text(family='ArialMT',colour='black',face='bold',size=16),
         legend.text=element_text(family='ArialMT',colour='black',face='bold',size=14))

```


```{r function, echo=FALSE}

  F_replicateTec=function(patient,Tmpt){
 
    IS_to_keep=list()
    DF_all=DF_ab=DF_tot=list()

    for (tmpt in Tmpt){
    
      for (cell in 1:length(celltype)) {
      
      cellfilter=celltype[cell]
      rep=NA
      tec_repl=NA
      tec_replall=NA
      tec_repl_1=tec_repl_2=tec_repl_3=NA
      
      # Select the data
      i <- which(intSites$patient==patient & intSites$timePoint==tmpt & intSites$cellType%in%cellfilter)
      d <- intSites[i,]
      d$sampleName=as.character(d$sampleName)
      
      ## Get the biological replicates and regroup them if there are more than 2
      d_filt=subset(d,d$cellType==cellfilter)
      rep=unique(d_filt$GTSP)
      Nrep=length(rep)
      
       #********
       #***Case where there is only 1 bio. replicate***
       #********
      
        if(Nrep==1) {
        
        d=subset(d,d$GTSP==rep[1])
        
        #get the technical replicates
        tec_repl=unique(d$sampleName)
        
        #order the technical replicates by their numbers
        order=order(as.numeric(gsub('.*-','',tec_repl)))
        tec_repl=tec_repl[order]         
         
        #separate them in two groups   
        n=length(tec_repl)
        g1=1:(n/2)
        g2=((n/2)+1):n
        vec_part1=d[d$sampleName%in%tec_repl[g1],]
        vec_part2=d[d$sampleName%in%tec_repl[g2],]
        }

        
      #********  
      #***Case where there is more than 1 bio. replicate***
      #********
      
      if(Nrep>1){
        
        for (i in 1:Nrep) {
          
          #get the biological replicate i
          d_prov=subset(d,d$GTSP==rep[i])
          assign(paste0('d',i),d_prov)
          
          #get the technical replicates
          tec_repl_prov=unique(as.character(d_prov$sampleName))
          
          #order the technical rep. by their numbers
          order=order(as.numeric(gsub('.*-','',tec_repl_prov)))
          tec_repl_prov=tec_repl_prov[order]   
          assign(paste0('tec_repl_',i),tec_repl_prov)
          
          #get the nb of technical rep.
          n_prov=length( tec_repl_prov)
          assign(paste0('n',i),n_prov)
        }
      
        rm(d_prov)
        rm(tec_repl_prov)
        rm(n_prov)
      
        #get all the technical rep. present
        tec_replall=ls()[grep('tec_repl_.*', ls())]
        
        #Get the first biological replicate
        #separate its technical rep. in two groups 
        vec=get(tec_replall[1])
        g1=vec[1:(length(vec)/2)]
        g2=vec[((length(vec)/2)+1):length(vec)]
 
        #get the other biological values
        #gather them in the two groups, after division.
        for(i in 2:Nrep){
        vec=get(tec_replall[i])
        g1=c(g1,vec[1:(length(vec)/2)])
        g2=c(g2,vec[((length(vec)/2)+1):length(vec)])
        vec_part1=d[d$sampleName%in%g1,]
        vec_part2=d[d$sampleName%in%g2,]

        }
       
       rm(vec)
      }
 
    # Reorganize the data to create an intSite / cell count table. 
      
    #GROUP 1
    un <- reshape2::dcast(vec_part1, posid ~ cellType , value.var='estAbund', fun.aggregate=function(x){sum(x)}, fill=0)  
      
    #GROUP 2
    de <- reshape2::dcast(vec_part2, posid ~ cellType , value.var='estAbund', fun.aggregate=function(x){sum(x)}, fill=0)  
      
    ###############################
    # Apply Threshold to the data # 
    ###############################
      
    #define the abundance threshold
    thresh_b=6
  
    #Sum to obtain the total abundance of the cell studied by IS
    data_all_regroup=rbind(un,de)
    data_all=aggregate(data_all_regroup[,2],by=list(data_all_regroup$posid),sum)
    
    #in case there are not enough cells 
      if(max(data_all$x)<thresh_b) {
       thresh_b=max(data_all$x)
       cat('\n ')
       cat('** ! Not enough cells, new threshold =',thresh_b,'**')
       cat('\n ')
     }
    
    #Select the IS that have >= thresh_b cell studied, all replicates aggregated.
    data_all_threshold=filter(data_all,x>=thresh_b)
    IS_selected=unique( data_all_threshold$Group.1)
      
      
    ########################################################### 
    ## Correlation study between the two groups of tec. rep. ##  
    ########################################################### 
      
    data_plot=merge(un,de,all=TRUE,by='posid')
    data_plot[is.na(data_plot)]<-0
    data_plot$filter=factor(ifelse(data_plot$posid%in%IS_selected,1,0))
    colnames(data_plot)=c('IS','celltype.x','celltype.y','filter')
    data_plot$ab_tot=data_plot$celltype.x+data_plot$celltype.y
    
    #correlation  
    r=round(cor(data_plot$celltype.x,data_plot$celltype.y),3)
      
    #get the data with the threshold
    cut=data_plot[data_plot$filter==1,]
    
    #correlation 
    r_cut=round(cor(cut$celltype.x,cut$celltype.y),3)
      
    ## keep information to show in a recapitulative table.
    crossOv=crossOverReports[[paste0(patient,'|',tmpt,'|Blood')]]
    VCN=crossOv$VCN[c(3,2,1,4,5)]
    DNA=crossOv$DNA[c(3,2,1,4,5)]
    psort=crossOv$psort[c(3,2,1,4,5)]
      
    DF_ab[[cellfilter]]=data.frame(cell=cellfilter,r=r,r_cut=r_cut,nb_IS_filt=length(IS_selected),
    tmpt=tmpt,VCN=VCN[cell],DNA= DNA[cell],psort=psort[cell])

   }
    
  ##Stock the values fo each tmpt.    
  DF_tot[[tmpt]]=do.call(rbind,DF_ab)
    
  }
  
  ##Gather all the values in a table.
  DF_tot_all=do.call(rbind,DF_tot)
  rownames(DF_tot_all)<-NULL
  # print(kable(DF_tot_all,caption = paste('Threshold (b) info. : cell type >=',thresh_b)))
  # cat('\n')  
  
  
  ### Heatmap of the correlations :
  
  DF_tot_all$cell=factor(DF_tot_all$cell,levels=celltype,
                         labels=c('G','M','B','K','T'))
  
  patient=gsub('b','\u03B2',patient)
  
  hmap=ggplot(DF_tot_all,aes(x=tmpt,y=cell,fill=r_cut))+geom_tile()+  
     scale_fill_distiller(palette = "Spectral",limits = c(-1,1))+
     geom_text(aes(label=r_cut),colour='black', fontface = "bold",size=6)+
     scale_y_discrete(limits = rev(levels(DF_tot_all$cell)))+
     th_small+labs(title=patient,fill='r',x='',y='')  
  print(hmap)
  
  }

```

```{r CallFunc ,echo=FALSE, eval=TRUE,results='asis',warning=FALSE,message=FALSE,fig.width=8,fig.height=6}

## Calling the previous function

#BM patients
F_replicateTec(patient='WAS4',Tmpt=c('m12','m36','m48','m60'))
F_replicateTec(patient='WAS5',Tmpt= c('m12.6','m36','m43','m55'))
F_replicateTec(patient='bS/bS',Tmpt=c('m12','m24'))

#MPB patients
F_replicateTec(patient='WAS2',Tmpt=c('m22','m48','m78'))
F_replicateTec(patient='WAS7',Tmpt=c('m30','m48'))
F_replicateTec(patient='b0/bE',Tmpt=c('m11','m36','m48'))

```


