---
fontsize: 11pt
geometry: margin=0.25in
output:
  html_document:
    keep_md: no
---

```{r DataPrep, echo=FALSE, eval=TRUE,warning=FALSE,message=FALSE}

########################################################################
######################## DATA PREPARATION ##############################
########################################################################

###Loading the packages
library(plyr)
library(tidyverse)
library(reshape2)
library(lazyeval)
library(psych)
library(MASS)
library(scales)
library(gridExtra)
library(grid)
library(knitr)
library(gtools)
library(gtable)


##################################
### Data loading and formatting  ###
#################################



intSites_original <- read.table(gzfile('../data/intSites.noMergedSamples.csv.gz'), sep = ',', header = TRUE)

intSites <- data.frame(intSites_original) %>%
            dplyr::group_by(sampleName, posid) %>%
            dplyr::mutate(estAbund = n_distinct(paste(start, end))) %>%
            dplyr::mutate(reads = sum(reads)) %>%
            dplyr::slice(1) %>%
            GenomicRanges::makeGRangesFromDataFrame(keep.extra.columns = TRUE)

intSites=data.frame(intSites@elementMetadata)


 for(i in c('estAbund')) intSites[[i]] <- as.numeric(intSites[[i]]) 
 intSites$cellType=factor(intSites$cellType,levels=levels(intSites$cellType),
                          labels=c( "Bcells","Granulocytes" ,
                                    "Monocytes", "NKcells","Tcells" )) 


intSites$timePoint=tolower(intSites$timePoint)
intSites$key <- paste(intSites$posid, intSites$cellType, intSites$patient, intSites$timePoint)

```

```{r GlobalParameters,  echo=FALSE, message=FALSE, warning=FALSE}

##################################################################### 
####################### GLOBAL PARAMETERS ###########################
##################################################################### 

celltype=c( "Granulocytes", "Monocytes", "Bcells", "NKcells", "Tcells")

# Determine general element themes for the plots:

th_small=theme_bw()+
   theme(text=element_text(family='ArialMT',size=36, colour='black',face='bold'),
         panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
         strip.background=element_rect(fill=NA, color=NA),
         strip.text=element_text(family='ArialMT',size=65,colour='black',face='bold'),
         axis.text=element_text(family='ArialMT',size=31, colour='black',face='bold'),
         plot.title=element_text(family='ArialMT',size=65, colour='black',face='bold'),
         legend.text=element_text(family='ArialMT',size=34 ,colour='black',face='bold'))

```
  
## Replicates study
  
```{r Function_replicate_study, echo=FALSE, eval=TRUE,warning=FALSE,message=FALSE}

  F_replicateTec=function(patient,tmpt,cellFilt,thresh_bar,example){
  
  IS_to_keep=list()
  DF_all=DF_ab=DF_rep=all_plot=list()
  all_plot=list()
  
  for (cellfilter in cellFilt) {
    
  # Select the data
  i <- which(intSites$patient==patient & intSites$timePoint==tmpt & intSites$cellType%in%cellfilter)
  d <- intSites[i,]

  ## Get the biological replicates and select the 1st
  d_filt=subset(d,d$cellType==cellfilter)
  rep=unique(d_filt$GTSP)
  d=subset(d,d$GTSP==rep[1])

  ## Get the technical replicates
  tec_repl=unique(d$sampleName)
  n=length(tec_repl)

  #order the technical replicates by their numbers
  order=order(as.numeric(gsub('.*-','',tec_repl)))
  tec_repl=tec_repl[order]         
         
  #split them in two groups   
  g1=1:(n/2)
  g2=((n/2)+1):n
  vec_part1=d[d$sampleName%in%tec_repl[g1],]
  vec_part2=d[d$sampleName%in%tec_repl[g2],]
  
  
  # Reorganize the data to create an intSite / cell count table. 
      
    #GROUP 1
    un <- reshape2::dcast(vec_part1, posid ~ cellType , value.var='estAbund', fun.aggregate=function(x){sum(x)}, fill=0)  
      
    #GROUP 2
    de <- reshape2::dcast(vec_part2, posid ~ cellType , value.var='estAbund', fun.aggregate=function(x){sum(x)}, fill=0)  
      
    ###############################
    # Apply Threshold to the data # 
    ###############################
      
    #define the abundance threshold
    thresh_b=6
  
    #Sum to obtain the total abundance of the cell studied by IS
    data_all_regroup=rbind(un,de)
    data_all=aggregate(data_all_regroup[,2],by=list(data_all_regroup$posid),sum)
    
    #in case there are not enough cells 
      if(max(data_all$x)<thresh_b) {
       thresh_b=max(data_all$x)
       cat('\n ')
       cat('** ! Not enough cells, new threshold =',thresh_b,'**')
       cat('\n ')
     }
    
    #Select the IS that have >= thresh_b cell studied, all replicates aggregated.
    data_all_threshold=filter(data_all,x>=thresh_b)
    IS_selected=unique( data_all_threshold$Group.1)
      
  # --- Data total with threshold in color:
 
    ########################################################### 
    ## Correlation study between the two groups of tec. rep. ##  
    ########################################################### 
      
    data_plot=merge(un,de,all=TRUE,by='posid')
    data_plot[is.na(data_plot)]<-0
    data_plot$filter=factor(ifelse(data_plot$posid%in%IS_selected,1,0),
                            levels=c(0,1),
                            labels=c(paste('Ab. <',thresh_b),paste('Ab. >=',thresh_b)))
    colnames(data_plot)=c('IS','celltype.x','celltype.y','filter')
    data_plot$ab_tot=data_plot$celltype.x+data_plot$celltype.y
    
    
    #get the data with threshold
    cut=data_plot[data_plot$filter==paste('Ab. >=',thresh_b),]
    r=round(cor(cut$celltype.x,cut$celltype.y),3)
    
    
  ## Scatter plot comparing the 2 groups of tec. rep
  a=ggplot(data_plot,aes(x=celltype.x,y=celltype.y,color=filter))+geom_count()+
    labs(x='Group 1',y='Group 2')+
    labs(subtitle=paste('r=',r),size='n')+
    th_small+theme(aspect.ratio=1,legend.position='bottom')+
    guides(colour=guide_legend(title='',override.aes = list(size=10),nrow=2,byrow=TRUE,order=1),
           size=guide_legend(nrow=2,byrow=TRUE,order=2))+    scale_size_continuous(breaks = round,range=c(3, 15))
  
    
  #### Test of different abundance threshold
    
  bplot=list()
  
  #define the different abundance threshold

  for(thresh_b2 in thresh_bar){

  #in case there are not enough cells 
      if(max(data_all$x)<thresh_b2) {
       thresh_b2=max(data_all$x)
       cat('\n ')
       cat('** ! Not enough cells, new threshold =',thresh_b2,'**')
       cat('\n ')
     }

  data_plot=merge(un,de,all=TRUE,by='posid')
  colnames(data_plot)=c('IS','celltype.x','celltype.y')
  data_plot[is.na(data_plot)]<-0
  
  #calcul of the ratio G2/G1
  data_plot$quotient=data_plot$celltype.y/data_plot$celltype.x

 #select the IS matching the criteria
  
  data_all_threshold=filter(data_all,x>=thresh_b2)
  IS_selected=unique( data_all_threshold$Group.1)
  data_plot_s=subset(data_plot,data_plot$IS%in%IS_selected)

 #cut the ratio G2/G1 in categories
 data_plot_s$cat=cut(data_plot_s$quotient,breaks=c(-Inf,0.1,0.2,0.33,0.66,1.5,3,5,10,Inf),  right=T, include.lowest = TRUE)

   ## Barplot of the ratio of the two tec. rep. groups
   B=ggplot(data_plot_s)+geom_bar(aes(x=cat))+
    labs(y='',x='G1')+
    th_small+
    scale_x_discrete(drop=FALSE,breaks=levels( data_plot_s$cat),
                     labels= c(">10", ">5", ">3",">1.5","1",">1.5",">3",">5",">10"))+
    theme(axis.text.x = element_text(angle = 90,family='ArialMT',size=25, colour='black',face='bold',hjust=0.95,vjust=0.4),
          axis.title.x=element_text(hjust=0,family='ArialMT',size=38, colour='black',face='bold'))

  #add the second part of the x-axis title
  g = ggplotGrob(B)
 
  g2 <- gtable_add_grob(g, textGrob('G2', hjust=1,x=1,
                                    gp=gpar(fontfamily='ArialMT',fontsize=38,col='black',fontface='bold')),
                        t=8, l=4,  r=4, name="right-title",z=11)
  
  graph=g2
  graph$layout$clip = "off"

  bplot[[as.character(thresh_b2)]]=graph
  
  }

  all_plot[[cellfilter]] = arrangeGrob(a,graph,ncol=1,
                                      top=textGrob(paste0(cellfilter,'\n'),
                                                   gp=gpar(fontfamily='ArialMT',fontsize=51, col='black',fontface='bold')))
  
  
  }
  

  
    if (example==TRUE){
    return(list(A=a,B=bplot)) }
  
  
  if (example==FALSE){  
  patient=gsub('b','\u03B2',patient)  
    
  grid.arrange(all_plot[[1]],all_plot[[2]],all_plot[[3]],all_plot[[4]],all_plot[[5]],nrow=1,
             top=textGrob(paste('\n',patient,' ',tmpt,'\n'),
                          gp=gpar(fontfamily='ArialMT',fontsize=52, col='black',fontface='bold')))
 }
  
  cat('\n','  ','\n')
  
}


```


###### _Example : WAS4 m48 Granulocytes_ 

```{r, echo=FALSE, eval=TRUE,results='asis',warning=FALSE,message=FALSE,fig.width=25,fig.height=10}

### Example 

cat("\n")
cat("************ WAS4 ************")
cat("\n")

IS=F_replicateTec(patient='WAS4',tmpt='m48',cellFilt=c('Granulocytes'),thresh_bar=c(1,3,6,7),example=TRUE)

#plot A
print(IS$A+theme(legend.position = 'right'))

#plot B

B_plots=IS$B

B=lapply(1:length(B_plots), function(k){

ti=paste("Ab. >=",names(B_plots)[k])
title <- textGrob(ti, gp = gpar(fontsize = 50))
padding <- unit(0.5,"line")
B_plots[[k]] <- gtable_add_rows(B_plots[[k]], heights = grobHeight(title) + padding, pos = 0)
B_plots[[k]] <- gtable_add_grob(B_plots[[k]], list(title),t = 1, l = 1, r = ncol(B_plots[[k]]))
})

grid.arrange(grobs=B,nrow=1)

```


###### _All values_ 

```{r, echo=FALSE, eval=TRUE,results='asis',warning=FALSE,message=FALSE,fig.width=35,fig.height=20}

F_replicateTec(patient='WAS4',tmpt='m48',cellFilt=c('Granulocytes','Monocytes','Bcells','NKcells','Tcells'),
                 thresh_bar=6,example=FALSE)

F_replicateTec(patient='WAS5',tmpt='m55',cellFilt=c('Granulocytes','Monocytes','Bcells','NKcells','Tcells'),
                 thresh_bar=6,example=FALSE)

F_replicateTec(patient='bS/bS',tmpt='m24',cellFilt=c('Granulocytes','Monocytes','Bcells','NKcells','Tcells'),
                 thresh_bar=6,example=FALSE)

F_replicateTec(patient='b0/bE',tmpt='m48',cellFilt=c('Granulocytes','Monocytes','Bcells','NKcells','Tcells'),
                 thresh_bar=6,example=FALSE)

```